### ISSUE TITLE
include tests in gem file

### ISSUE THREAD

**Issue by pravi** [k0kubun/hamlit#79] opened 2016-07-24 09:50 UTC
I'm packaging hamlit for debian and would like to have tests enabled when creating the deb file. We usually take the github tarballs directly, but its missing houdini. So we have to manually recreate a source tarball that both houdini and tests.

**Comment by k0kubun** [comment] 2016-07-24 10:51
Thank you for your effort of packaging Hamlit. 

Tests are in the repository. Do you mean you want Hamlit to stop using git submodule of houdini copy it?

**Comment by pravi** [comment] 2016-07-24 11:03
@k0kubun it would be easier if you just add 'test' in gem releases. Copying houdini will also work.

**Comment by k0kubun** [comment] 2016-07-24 12:21
> if you just add 'test' in gem releases

Actually tests are excluded from rubygems package. https://github.com/k0kubun/hamlit/blob/v2.5.0/hamlit.gemspec#L17

Excluding tests is (bundler template's) default config and including tests increases the size of package. I'm reluctant to do that.

> Copying houdini will also work.

Hmm... I confirmed that tarball does not have neither houdini nor .git. Git submodule is harmful in some ways, so personally I'm okay to do this. I'll do that later. For now, I recommend you to manually download houdini and extract it to ext/hamlit/houdini since I think it's not responsibility of Hamlit but packaging.

**Comment by k0kubun** [comment] 2016-07-24 12:25
Ah, maybe we can add tarball that has houdini to releases for each release. Since it's not default, I need research how to do it.

**Comment by k0kubun** [comment] 2016-08-14 14:28
Dropped git submodule of houdini in https://github.com/k0kubun/hamlit/pull/82. So closing for now. Feel free to reopen this if you still have a problem.

**Closed by k0kubun** 2016-08-14 14:28 UTC
