### ISSUE TITLE
Hyphenate aria attribute in addition to data attribute

### ISSUE THREAD

**Issue by francesco-loreti** [k0kubun/hamlit#57] opened 2016-02-16 14:33 UTC
Into file .haml
`%nav{role: "navigation", :aria => { label: t('You are here', default: 'You are here:') } }`
Parse with HAML(correct)
`<nav aria-label="You are here:" role="navigation"></nav>`
Parse with HAMLIT(incorrect)
`<nav aria="{:label=>&quot;You are here:&quot;}" role="navigation"></nav>`

**Comment by k0kubun** [comment] 2016-02-16 14:41
Yeah that's true. It's a specification of Hamlit for optimization.
https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#limited-attributes-hyphenation

`%nav{role: "navigation", :data => { label: t('You are here', default: 'You are here:') } }` will be rendered correctly. Hash nesting is allowed only for `data` attribute.

**Comment by k0kubun** [comment] 2016-02-16 14:44
By the way, why do you use `aria-label` attribute? Is there any library requiring such an attribute?

**Comment by francesco-loreti** [comment] 2016-02-16 14:47
It's described into Zurb Foundation 6 at this page
http://foundation.zurb.com/sites/docs/breadcrumbs.html

**Comment by k0kubun** [comment] 2016-02-16 14:53
Thank you for the information.  So you can't avoid using `aria-label` attribute.

Personally I would write such attributes as `%nav{role: "navigation", 'data-label': t('You are here', default: 'You are here:') }`. The syntax is allowed after Ruby 2.2. Do you like to use nested syntax?

**Comment by francesco-loreti** [comment] 2016-02-16 14:57
Yes I know this syntax :+1: 
It was just to report the error .

**Comment by k0kubun** [comment] 2016-02-16 15:08
I see, thank you for using Hamlit and reporting the issue :+1: 
It's a kind of trade-off in Hamlit. Of course I can implement an option to switch the behavior for you. But it'll increase the complexity of Hamlit and decrease the maintainability.

While at least I won't do that in Hamlit v2, I'm okay to provide it in Hamlit v3 or later. Closing for now but feel free to reopen this if you want that.

**Comment by RobWu** [comment] 2017-06-22 12:11
ARIA:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by RobWu** [comment] 2017-06-22 12:16
Aria is also define in https://html.spec.whatwg.org/#wai-aria

**Comment by k0kubun** [comment] 2017-06-22 13:23
Oh, actually I didn't know aria was a such kind of thing. 

Considering its semantics, adding aria to [hyphenated attribute](https://github.com/k0kubun/hamlit/blob/v2.7.2/REFERENCE.md#limited-attributes-hyphenation) sounds reasonable. Since such change won't degrade performance of templates that don't use aria attribute, I'm +1 to opt-in aria support.

**Comment by Napolskih** [comment] 2017-08-15 07:23
Hi
We have a big project, about 200 private gems.
We really want to switch to hamlit, but these restrictions with data attributes do not allow us to do this. Please implement this feature, let it be turned off by default and do not create lags.

**Comment by k0kubun** [comment] 2017-08-15 07:29
Confirmation: You need `aria`, right?

**Comment by k0kubun** [comment] 2017-08-15 07:34
This issue is only mentioning about not `data` attribute but `aria` attribute. And I'm going to enable `aria` support by default and have no way to disable it. This would be the first step.

Then, I also think it's okay to globally allow hyphenation for all attributes because recently I found that CRuby doesn't degrade performance by that. So probably your wish would be achieved. Anyway I want to confirm your motivation first.

**Comment by Napolskih** [comment] 2017-08-15 07:36
I need data attributes with an underscore like in Haml, with the hyphenate_data_attrs option.

**Comment by k0kubun** [comment] 2017-08-15 07:40
Ah, got it. It's anther issue from this issue. I'll think about it.

**Comment by k0kubun** [comment] 2017-08-15 07:57
> I need data attributes with an underscore like in Haml, with the hyphenate_data_attrs option.

Do you mean you specify `hyphenate_data_attrs: false` unlike default? I couldn't find any difference between default haml and hamlit in data attribute. You should write example Haml template, expected output in Haml and actual output in Hamlit.

**Comment by k0kubun** [comment] 2017-08-15 07:58
like this

```
$ haml -v
Haml 5.0.1
$ hamlit version
2.8.0
$ cat ,a.haml
- data = { 'a_b' => 'c' }
%div{data: data }
$ haml ,a.haml
<div data-a-b='c'></div>
$ hamlit ,a.haml
<div data-a-b='c'></div>
```

**Comment by Napolskih** [comment] 2017-08-16 07:35
```
development> Haml::VERSION
=> "4.0.7"
development> Haml::Engine.new("%a{ data: { 'product_id' => 'bar' } }").render
=> "<a data-product-id='bar'></a>\n"
development> Haml::Engine.new("%a{ data: { 'product_id' => 'bar' } }", hyphenate_data_attrs: false).render
=> "<a data-product_id='bar'></a>\n" (!!! I need this to replace haml -> hamlit)

development> Hamlit::VERSION
=> "2.8.4"
development> Hamlit::Engine.new.call("%a{ data: { 'product_id' => 'bar' } }")
=> "_buf = \"<a data-product-id='bar'></a>\\n\""
```

**Comment by k0kubun** [comment] 2017-08-16 07:48
Okay, I understood. Thank you for explanation.

Unfortunately, increasing the number of options may spoil the performance. So I need to implement it carefully. I'll consider it anyway.

By the way, very easy and also readable workaround is rewriting template like this:

```haml
%a{ 'data-product_id': 'bar' }
```

It's quite easy to understand the behavior, isn't it?

**Comment by Napolskih** [comment] 2017-08-16 08:57
The problem is that it is a huge monolith of 200 gems and it works on haml. And translating to hamlit is just an experiment that does not make it clear whether something good works or not. And for the sake of this there is no way to edit a bunch of code.

**Comment by dgilperez** [comment] 2018-10-16 08:34
I'd also would like to see `aria` (and just `aria`) to behave as `data`. It's a common case (actually, less common that it should!) and there's already plenty of code out there using the hash format. I think this will be an increasing source of errors / missformats due to people forgetting that `aria` just doesn't work as `data` and like the example they read ...

**Closed** 2018-10-16 11:30 UTC

**Comment by k0kubun** [comment] 2018-10-16 11:38
Thanks for heads up. I finally supported this in v2.9.0. Please try that.
