### ISSUE TITLE
Overriding "class" in a div doesn't work

### ISSUE THREAD

**Issue by andrewfader** [k0kubun/hamlit#116] opened 2017-11-06 01:26 UTC
I'm doing something like this

`%div.price{class: song.up_or_down?}
`

It works fine in vanilla haml, but in hamlit it instead returns some number for the method (should return a string)

**Comment by k0kubun** [comment] 2017-11-06 01:37
It's not reproductive:

```html
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

$ hamlit version
2.8.4

$ cat ,a.haml
- song = Object.new
- def song.up_or_down?; true; end
%div.price{class: song.up_or_down?}

$ hamlit ,a.haml
<div class='price true'></div>
```

Could you see https://github.com/k0kubun/hamlit#reporting-an-issue and provide mode details?

**Comment by andrewfader** [comment] 2017-11-06 01:49
Make your file return a string and it produces this

```
$ cat test.haml 
- song = Object.new
- def song.up_or_down?; "hello"; end
%div.price{class: song.up_or_down?}
 $  hamlit test.haml 
<div class='20641625616 price'></div>
```

**Comment by k0kubun** [comment] 2017-11-06 02:11
Thanks for details.

As it's fixed on master branch (but not released because there are still other problems with 2.5), I'll release next version for you.

**Comment by k0kubun** [comment] 2017-11-06 02:13
Done.

```
$ ruby -v
ruby 2.5.0dev (2017-10-04 trunk 60116) [x86_64-darwin16]
/Users/kokubun/src/github.com/k0kubun/hamlit status: 0                                                                                                            (git)-[master]-
$ hamlit version
2.8.5
/Users/kokubun/src/github.com/k0kubun/hamlit status: 0                                                                                                            (git)-[master]-
$ cat test.haml
- song = Object.new
- def song.up_or_down?; "hello"; end
%div.price{class: song.up_or_down?}
/Users/kokubun/src/github.com/k0kubun/hamlit status: 0                                                                                                            (git)-[master]-
$ hamlit test.haml
<div class='hello price'></div>
```

**Closed by k0kubun** 2017-11-06 02:13 UTC

**Comment by andrewfader** [comment] 2017-11-06 02:28
Thanks! 👍
