### ISSUE TITLE
Boolean attribute required not ignored when provided false value

### ISSUE THREAD

**Issue by jeffblake** [k0kubun/hamlit#24] opened 2015-05-12 06:58 UTC
If I do something like

`= f.text_field :value, required: false`

I would expect the output to ignore that tag. The current output is `required="false"`... which is actually interpreted as true by browsers.

**Comment by k0kubun** [comment] 2015-05-14 23:34
This can't be reproduced in my environment.
The `required: false` is compiled by not Hamlit but ActionView. Because `text_field` ignores `required` option [★](https://github.com/rails/rails/blob/22ae449/actionview/lib/action_view/helpers/tag_helper.rb#L157-L158), it may not be reproduced.

By the way, the ActionView's list of boolean attributes may be better than hamlit's one. So I changed hamlit to use the same one. Maybe your problem will be fixed by this change.

**Closed** 2015-05-14 23:33 UTC

**Comment by k0kubun** [comment] 2015-05-14 23:37
Released as v1.2.1 :gem:
